language: go
go:
  - tip
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
script:
    - go version
    - go test -v -cover -coverprofile=cover.out ./...
    - $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
    - golangci-lint run ./...
